# Generated by Django 2.1.2 on 2018-12-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_plans',
            fields=[
                ('Name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('Plan_Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('password', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Idno', models.IntegerField()),
                ('Name', models.CharField(max_length=500)),
                ('Contact_no', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=500, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sugesstion',
            fields=[
                ('suggestions', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgym.Registration')),
            ],
        ),
        migrations.CreateModel(
            name='View_suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='password',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgym.Registration'),
        ),
    ]
